---
- name: Bootstrap node - pt. 1
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: osism.commons.resolvconf
    - role: osism.commons.repository

- name: Bootstrap node - pt. 2
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Packages
      ansible.builtin.include_vars:
        file: "{{ ansible_os_family }}.yml"

  vars:
    ansible_python_interpreter: /usr/bin/python3

    # cleanup
    cleanup_services_extra:
      - NetworkManager
      - iscsid
      - lxcfs
      - nscd
      - ntp
    cleanup_packages_extra:
      - dosfstools
      - ntfs-3g
      - telnet

    # packages
    upgrade_packages: false

    # operator
    operator_user: dragon
    operator_group: dragon
    operator_authorized_keys:
      - "{{ lookup('file', '/home/install/.ssh/id_rsa.pub') }}"

  roles:
    - role: osism.services.chrony
    - role: osism.commons.systohc
    - role: osism.commons.configfs
    - role: osism.commons.packages
    - role: osism.commons.sysctl
    - role: osism.commons.services
    - role: osism.commons.motd
    - role: osism.services.hddtemp
    - role: osism.services.rng
    - role: osism.commons.cleanup
