#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

echo $DIB_OSISM_HOSTNAME > /etc/hostname

# change console font

sed -i 's/FONTFACE="Fixed"/FONTFACE="Terminus"/' /etc/default/console-setup
sed -i 's/FONTSIZE="8x16"/FONTSIZE="16x32"/' /etc/default/console-setup
update-initramfs -u


# disable systemd-networkd-wait-online service

systemctl disable systemd-networkd-wait-online.service

# disable ironic-python-agent service

systemctl disable ironic-python-agent.service
