#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$TMP_HOOKS_PATH" ] || die "Temp hook path not set"

cat files/metalbox/part1.yml > $TMP_HOOKS_PATH/part1.yml
cat files/metalbox/part2.yml > $TMP_HOOKS_PATH/part2.yml
cat files/metalbox/run.sh > $TMP_HOOKS_PATH/run.sh
cat files/metalbox/99_metalbox.cfg > $TMP_HOOKS_PATH/99_metalbox.cfg
