#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


sudo apt update
sudo apt -y upgrade

sudo mkdir -p $TARGET_ROOT/EFI/BOOT

sudo cp -a /boot/efi/EFI/BOOT/BOOTX64.EFI $TARGET_ROOT/EFI/BOOT/BOOTX64.EFI
sudo cp -a /usr/lib/grub/x86_64-efi/monolithic/grubx64.efi $TARGET_ROOT/EFI/BOOT/GRUBX64.EFI
