#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

cp /tmp/in_target.d/50-metalbox-carrier.yaml /etc/netplan/50-metalbox-carrier.yaml
chmod 0600 /etc/netplan/50-metalbox-carrier.yaml
rm -f /etc/netplan/50-cloud-init.yaml

cp /tmp/in_target.d/91-metalbox-carrier.cfg /etc/cloud/cloud.cfg.d/91-metalbox-carrier.cfg
chmod 0644 /etc/cloud/cloud.cfg.d/91-metalbox-carrier.cfg

systemctl disable multipathd
systemctl disable multipathd.socket

apt-get install -y cifs-utils nfs-common

apt-get remove -y modemmanager snapd unattended-upgrades apport
apt-get autoremove -y
