#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

# TODO(frickler): avoid this workaround
if [ -f /boot/grub/x86_64-efi/mdraid1x.mod ]; then
    cp /boot/grub/x86_64-efi/mdraid1x.mod /boot/efi/EFI/BOOT
fi

rm -f /etc/default/grub.d/50-cloudimg-settings.cfg
update-grub
grub-install --modules=mdraid1x -v

