---
- name: Run bootstrap - part 1
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # operator
    operator_user: dragon
    operator_group: dragon
    operator_password: $6$uBNqcH/eR0dQ2wxA$Zeb/dLBKStIq4gFxgUKKmrnCs4uGlGQoCby/G9CSfAJE2VzTb8ofm.HCYzmKJXkzIXIjdQL1xeDoI3b9GAvVX.
    operator_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIquLz7xZ1rzpsoivjOiZTarg+jri0ezRn823wGw4G0gFfosxPxNJ4BS1LaGjje9YI4JVsU2btDuxcNIvmRehVLPHxRwpDHE+FVajltnF1DQXiySitdbC27N1NIaVbWv8y1C2PFnXL+QUrF2VddOzNnMBXingEV2Ev/bTW/XfVTTArpHsNTS0DJRMpMeUROHmCwxhWjjuFfCcH2EEn5KyBCvgiQIozkwf5Q7nK3DeG2QODxtLPJkmCEuvpqbwZF8VkaE1n1TLr7a9CD/p4sn1+Z1BJO+Zsg72AM9A0lKQ0/1TCsAHLMIoZoNH2F7JeNtApFhDAEg9EZGyk0RDkrKxojYzuimvoyYXI84JDdKx3kDFGiXB3ITDMOFRajGLdgJwAZT2Aw62H0uWQs1dMNRtMgaemLIDmschZDVH5j9iDwEZaKVzJ6LLDSn1Wl09nuZNV8okNIvsBe4X6mHzqwLOYYga/HmI6y4nudTLSeckFraMXGRFFfGHDVpNwKRRavx0= dragon@osism
    operator_private_key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAYEAyKri8+8Wda86bKIr4zomU2q4Po64tHs0Z/Nt8BsOBtIBX6LMT8TS
      eAUtS2ho43vWCOCVbFNm7Q7sXDSL5kXoVSzx8UcKQxxPhVWo5bZxdQ0F4skorXWwtuzdTS
      GlW1r/MtQtjxZ1y/kFKxdlXXTszZzAV4p4BFdhL/201v131U0wK6R7DU0tAyUTKTHlETh5
      gsMYVo47hXwnB9hBJ+SsgQr4IkCKM5MH+UO5ytw3htkDg8bSzyZJghLr6am8GRfFZGhNZ9
      Uy6+2vQg/6eLJ9fmdQSTvmbIO9gDPQNJSkNP9UwrAByzCKGaDR9heyXjbQKRYQwBIPRGRs
      pNEQ5KysaI2M7opr6MmFyPOCQ3Ssd5AxRolwdyEwzDhUWoxi3YCcAGU9gMOth9LlkLNXTD
      UbTIGnpiyA5rHIWQ1R+Y/Yg8BGWilcyeiyw0p9VpdPZ7mTVfKJDSL7AXuF+ph86sCzmGIG
      vx5iOsuJ7nUy0nnJBa2jFxkRRXxhw1aTcCkUWr8dAAAFiJgUI1iYFCNYAAAAB3NzaC1yc2
      EAAAGBAMiq4vPvFnWvOmyiK+M6JlNquD6OuLR7NGfzbfAbDgbSAV+izE/E0ngFLUtoaON7
      1gjglWxTZu0O7Fw0i+ZF6FUs8fFHCkMcT4VVqOW2cXUNBeLJKK11sLbs3U0hpVta/zLULY
      8Wdcv5BSsXZV107M2cwFeKeARXYS/9tNb9d9VNMCukew1NLQMlEykx5RE4eYLDGFaOO4V8
      JwfYQSfkrIEK+CJAijOTB/lDucrcN4bZA4PG0s8mSYIS6+mpvBkXxWRoTWfVMuvtr0IP+n
      iyfX5nUEk75myDvYAz0DSUpDT/VMKwAcswihmg0fYXsl420CkWEMASD0RkbKTREOSsrGiN
      jO6Ka+jJhcjzgkN0rHeQMUaJcHchMMw4VFqMYt2AnABlPYDDrYfS5ZCzV0w1G0yBp6YsgO
      axyFkNUfmP2IPARlopXMnossNKfVaXT2e5k1XyiQ0i+wF7hfqYfOrAs5hiBr8eYjrLie51
      MtJ5yQWtoxcZEUV8YcNWk3ApFFq/HQAAAAMBAAEAAAGARLcP5IxY2o/Yp96YvMTq3uHKmd
      Fxuov+FCKt4OzCzt8XDVLIOACkOek763ijglKjpoKRaHje5AqaMbDkv0PtHU24w/CZuQV2
      zafZoF/rVjPRcimEPnHww5M07Pa6kyAEB7nUqAz+5YwukuT+FxS1CmvFCbUnCAWMCE0Ooh
      hF8srt1eQLJzDoWw1VFGQ7lrwKEBcSvIEULM+o5ezN0wVhdQb2lXQYXzTYJClm8+qZMRob
      NALfqYPo5BvqoSc4fDdBC66irsPzc6jTqVVvnmBD/lDWNUW+etac62GQVnjf/KrEWWtTXs
      dIIwbXl5uTutug22KZbxOcwFwxd2U20I6/yBq+KYk3OE6IXe2He5FiHi9UdtAgTPdCvgC1
      WUDGl7A6Y5/UPbNhrNk15qdf6Yhc9jauPq3drOVZhzIR2j948ilYcnJAKsJ49ETibkCB3f
      rrElOPhtqgGOv3XVy9xiXbTyl0UoxYif0y+lbxu2KrBio6pneCwAku1jvorpDc7DQBAAAA
      wQCzIDfihgw6WJ1p+DHrLdwqYAR070un4IrpuRMk+BlgoT/pJ3/scrXO69hWC3g+Gm8C/A
      NpF03NKBadhhOoFd8KhEQy4EDassPVq80TRF6/PibsrtNXDUW3XWmZYt1c+9YUSFNI2qKC
      bQD8A55oG+ZRnNgdVGwgN79oQdl6wE1lPKxrHjLXSCMCjtmnlvZgJw9MeKchQ5OI9vVmX1
      AHLJm9mY4FTo+ti5HhHkO+R7zT3uD1vZGM9JV9LnUipzpf9YMAAADBAOfPho1Ci9f1O6Sv
      dZw68XQ2DEMzBWtPpBWd+Q0Vixzl4V5XHtwk4IwMyIwGGmX+k76g3XiCPYQkBIrMuPZSnu
      I1ZyhdPiBUV433Hel/+dJNQJd/7qffd63dBw9mySSTQbkIJff8rXWE1OY40sWovp4A+vMO
      2P7ZeyRVHmLgI7Kn52s+pK+MnVmTuvcpSAtk/2/Rzkw4DU1qsrcnzbDlvtDD6RuhwN6F6/
      732lG3LFCImpmLnXdz2K/ph1oSWVd/gQAAAMEA3ZtrSKUbY9z9qaN9uPJC4+xcQE2ZPzNT
      jCPFljk8Ne6YAcUhseVHMmDJ5N14aZGaZkQj3FhcDU7IG/LL/Yc+hTKXkao3O89bq99g/D
      OlcOLQ2ydEYYB3SOOOhS9plCnyXGs3LuSe1YRyLROG9NRtTobUSjbQ6syR9lOrYhtgYo5n
      yaFXVfGLN8ZsvMxdY1kmw30JwUfujXxkR3ojtLzY70Ki1DAZOSni7nDpO8muD1DIJV+JNb
      mzrUzkLbT0OA2dAAAAD2luc3RhbGxAaW5zdGFsbAECAw==
      -----END OPENSSH PRIVATE KEY-----

    # cleanup
    cleanup_cloudinit: false
    cleanup_packages_extra:
      - apport
      - snapd

    # packages
    required_packages_extra:
      - ca-certificates
      - frr
      - htop
      - ipmitool
      - iptables
      - linux-generic-hwe-24.04
      - net-tools
      - python3-netaddr
      - rsync
      - skopeo
      - socat
      - sosreport
      - tcpdump
      - tmux
      - tuned
      - wireguard-tools

    # hostname
    hostname_name: metalbox

    # hosts
    hosts_type: template
    hosts_additional_entries:
      api.metalbox.osism.xyz: 192.168.42.10

  roles:
    - osism.commons.hostname
    - osism.commons.hosts
    - osism.commons.repository
    - osism.commons.microcode
    - osism.services.rsyslog
    - osism.commons.operator
    - osism.commons.systohc
    - osism.commons.configfs
    - osism.commons.packages
    - osism.commons.sysctl
    - osism.commons.limits
    - osism.commons.services
    - osism.commons.motd
    - osism.services.rng
    - osism.commons.cleanup
    - osism.services.chrony
    - osism.services.journald
    - osism.services.lldpd

- name: Apply role docker
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # renovate: datasource=github-releases depName=moby/moby
    docker_version: '5:27.5.1'
    docker_facts: false
    docker_insecure_registries:
      - localhost:5000

  roles:
    - osism.services.docker

- name: Apply role docker_compose
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    docker_compose_install_type: package

  roles:
    - role: osism.commons.docker_compose
