---
- name: Run bootstrap - part 2
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    network_ethernets:
      eth*:
        dhcp4: false
        dhcp6: false
        link-local: [ipv6]
      en*:
        dhcp4: false
        dhcp6: false
        link-local: [ipv6]
      enp*:
        dhcp4: false
        dhcp6: false
        link-local: [ipv6]
      eno*:
        dhcp4: false
        dhcp6: false
        link-local: [ipv6]

    network_dummy_devices:
      dummy0:
        addresses:
          - 192.168.42.10/24

  roles:
    - osism.commons.network

  tasks:
    - name: Create /etc/metalbox file
      ansible.builtin.copy:
        content: 1
        dest: /etc/metalbox
        owner: root
        group: root
        mode: 0644
