#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

export LANG=en_US.UTF-8
export LANGUAGE=en_US
export LC_ALL=

export PATH=/root/.local/bin:$PATH

# run part 1

ansible-playbook -i localhost, /root/part1.yml

# clone configuration repository

git clone https://github.com/osism/metalbox /opt/configuration
chown -R dragon:dragon /opt/configuration

# prepare manager environment

pushd /opt/configuration/environments/manager
sudo -u dragon bash run.sh noop
sed -i 's/\(INSTALL_ANSIBLE_ROLES=${INSTALL_ANSIBLE_ROLES:-\)true/\1false/' /opt/configuration/environments/manager/run.sh
popd

# prepare netbox environment

sudo -u dragon pipx install netbox-manager
sudo -u dragon pipx install 'ansible-core>=2.18.0,<2.19.0'
sudo -u dragon /home/dragon/.local/bin/ansible-galaxy collection install netbox.netbox

# download registry image

skopeo copy --dest-tls-verify=false docker://registry.osism.tech/dockerhub/library/registry:3 docker-archive:/opt/registry.tar:registry:3

# download alpine image

skopeo copy --dest-tls-verify=false docker://registry.osism.tech/dockerhub/library/alpine:3 docker-archive:/opt/alpine.tar:alpine:3

# download registry volume archive

if [[ "$DIB_METALBOX_DOWNLOAD_REGISTRY_ARCHIVE" == "true" ]] then
    wget -O /opt/registry.tar.bz2 https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/metalbox/registry.tar.bz2
fi

# download ironic images

if [[ "$DIB_METALBOX_IPA_IMAGES" == "true" ]] then
    wget -O /opt/ironic-agent.initramfs https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-centos9-stable-${DIB_METALBOX_OPENSTACK_RELEASE}.initramfs
    wget -O /opt/ironic-agent.kernel https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ipa-centos9-stable-${DIB_METALBOX_OPENSTACK_RELEASE}.kernel
fi

# change console font

sed -i 's/FONTFACE="Fixed"/FONTFACE="Terminus"/' /etc/default/console-setup
sed -i 's/FONTSIZE="8x16"/FONTSIZE="16x32"/' /etc/default/console-setup
update-initramfs -u

# run part 2

ansible-playbook -i localhost, /root/part2.yml

# cleanup

rm -f /etc/netplan/50-cloud-init.yaml
rm -rf /root/.ansible
