#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

apt-get install -y \
    memtester \
    stress-ng

cp /tmp/in_target.d/stress-ng.sh /usr/local/bin/stress-ng.sh
chmod +x /usr/local/bin/stress-ng.sh

cp /tmp/in_target.d/99_burnin.cfg /etc/cloud/cloud.cfg.d/99_burnin.cfg
chown root:root /etc/cloud/cloud.cfg.d/99_burnin.cfg
chmod 0644 /etc/cloud/cloud.cfg.d/99_burnin.cfg
