#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# DIB expects these directories. Let's remove them later
sudo mkdir -p ${TARGET_ROOT}/{sys,proc,dev,tmp,var/log,root}
