#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Set timezone
echo 'Etc/UTC' > /etc/timezone

# Create locale
echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
echo 'C.UTF-8 UTF-8' >> /etc/locale.gen
#locale-gen
