#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


sudo rm $TARGET_ROOT/etc/resolv.conf
sudo rm $TARGET_ROOT/etc/resolv.conf.ORIG
sudo rm $TARGET_ROOT/etc/fstab
sudo rmdir $TARGET_ROOT/etc
